//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockingSystemReminder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClockingSystemReminder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;approve&quot;:true,&quot;from&quot;:&quot;{0}T23:00:00.000Z&quot;,&quot;to&quot;:&quot;{1}T23:00:00.000Z&quot;,&quot;activeIdentity&quot;:{&quot;Username&quot;:&quot;{2}&quot;,&quot;EmployeeId&quot;:{3},&quot;PositionId&quot;:&quot;{4}&quot;,&quot;Description&quot;:&quot;{5}&quot;,&quot;ReadOnly&quot;:false,&quot;PositionIdValue&quot;:{6}},&quot;activeRole&quot;:1}.
        /// </summary>
        internal static string WinTidApprovePayload {
            get {
                return ResourceManager.GetString("WinTidApprovePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;model&quot;:{&quot;DisplayTwoFactorInput&quot;:false,&quot;KeyCode&quot;:&quot;&quot;,&quot;Password&quot;:&quot;{1}&quot;,&quot;RememberMe&quot;:false,&quot;UserName&quot;:&quot;{0}&quot;},&quot;returnUrl&quot;:null}.
        /// </summary>
        internal static string WinTidLoginPayload {
            get {
                return ResourceManager.GetString("WinTidLoginPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;activeIdentity&quot;:{&quot;EmployeeId&quot;:{0},&quot;PositionId&quot;:&quot;{1}&quot;,&quot;IsPrimary&quot;:true,&quot;Description&quot;:&quot;{2}&quot;},&quot;activeRole&quot;:1}.
        /// </summary>
        internal static string WinTidPayload {
            get {
                return ResourceManager.GetString("WinTidPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;date&quot;:&quot;{0}T22:00:00.000Z&quot;,&quot;weekly&quot;:false,&quot;activeIdentity&quot;:{&quot;EmployeeId&quot;:45,&quot;PositionId&quot;:&quot;7005960&quot;,&quot;IsPrimary&quot;:true,&quot;Description&quot;:&quot;7005960&quot;},&quot;activeRole&quot;:1}.
        /// </summary>
        internal static string WinTidSchedulePayload {
            get {
                return ResourceManager.GetString("WinTidSchedulePayload", resourceCulture);
            }
        }
    }
}
